export const lightGradientConfig = {
  preset: "custom" as const,
  color1: "#FFFFFF",
  color2: "#2b85e7",
  color3: "#FFFFFF",
  rotation: -50,
  proportion: 1,
  scale: 0.01,
  speed: 10.05,
  distortion: 0,
  swirl: 50,
  swirlIterations: 16,
  softness: 47,
  offset: -299,
  shape: "Checks" as const,
  shapeSize: 45,
};

export const darkGradientConfig = {
  preset: "custom" as const,
  color1: "#050505",
  color2: "#2b85e7",
  color3: "#FFFFFF",
  rotation: -50,
  proportion: 1,
  scale: 0.01,
  speed: 10.05,
  distortion: 0,
  swirl: 50,
  swirlIterations: 16,
  softness: 47,
  offset: -299,
  shape: "Checks" as const,
  shapeSize: 45,
};
