export const lightGradientConfig = {
  preset: "custom" as const,
  color1: "#f7fbff",
  color2: "#7a70ff",
  color3: "#00bfb7",
  rotation: -50,
  proportion: 1,
  scale: 0.01,
  speed: 7.2,
  distortion: 0,
  swirl: 38,
  swirlIterations: 12,
  softness: 58,
  offset: -299,
  shape: "Checks" as const,
  shapeSize: 45,
};

export const darkGradientConfig = {
  preset: "custom" as const,
  color1: "#050816",
  color2: "#212a6b",
  color3: "#7dd3fc",
  rotation: -50,
  proportion: 1,
  scale: 0.01,
  speed: 7.2,
  distortion: 0,
  swirl: 38,
  swirlIterations: 12,
  softness: 58,
  offset: -299,
  shape: "Checks" as const,
  shapeSize: 45,
};
